### ISSUE TITLE
334 House Robbery

### ISSUE THREAD

**Issue by LeeMax117** [LeeMax117/LeetCode_practise#1]
- [x] Submmit code by Jinglong
- [x] Submmit code by LeeMax
- [x] Discuss and imporve

**Comment by LeeMax117** [comment]
I have a comments here

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/robb.py

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/tree/master/LeeMax/377_House_Robbery
