### ISSUE TITLE
182. 查找重复的电子邮箱

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#10]
编写一个 SQL 查询，查找 Person 表中所有重复的电子邮箱。

示例：

+----+---------+
| Id | Email   |
+----+---------+
| 1  | a@b.com |
| 2  | c@d.com |
| 3  | a@b.com |
+----+---------+
根据以上输入，你的查询应返回以下结果：

+---------+
| Email   |
+---------+
| a@b.com |
+---------+
说明：所有电子邮箱都是小写字母。

- [x] submit code by yuyang

- [x] submit code by jinglong

- [x] discuss

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/duplicateEmail.sql

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/LeeMax/182._Duplicate%20Emails
