### ISSUE TITLE
632. Smallest Range（hard）

### ISSUE THREAD

**Issue by LeeMax117** [LeeMax117/LeetCode_practise#11]
You have k lists of sorted integers in ascending order. Find the smallest range that includes at least one number from each of the k lists.

We define the range [a,b] is smaller than range [c,d] if b-a < d-c or a < c if b-a == d-c.

Example 1:

Input:[[4,10,15,24,26], [0,9,12,20], [5,18,22,30]]
Output: [20,24]
Explanation: 
List 1: [4, 10, 15, 24,26], 24 is in range [20,24].
List 2: [0, 9, 12, 20], 20 is in range [20,24].
List 3: [5, 18, 22, 30], 22 is in range [20,24].

Note:

    The given list may contain duplicates, so ascending order means >= here.
    1 <= k <= 3500
    -105 <= value of elements <= 105.
    For Java users, please note that the input type has been changed to List<List<Integer>>. And after you reset the code template, you'll see this point.

- [x] code submitted by Jinglong
- [x] code submitted by LeeMax
- [x] discuss and improve

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/smallestRange_minPQ.py

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/LeeMax/smallestRange.py
