### ISSUE TITLE
106. Construct Binary Tree from Inorder and Postorder Traversal

### ISSUE THREAD

**Issue by LeeMax117** [LeeMax117/LeetCode_practise#12]
Given inorder and postorder traversal of a tree, construct the binary tree.

Note:
You may assume that duplicates do not exist in the tree.

For example, given

inorder = [9,3,15,20,7]
postorder = [9,15,7,20,3]

Return the following binary tree:

  3
   / \
  9  20
    /  \
   15   7

- [x] Jinglong's code
- [x] LeeMax's code
- [x] Discuss and imporve

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/tree/master/LeeMax/106.%20Construct_Binary_Tree_from_Inorder_and_Postorder_Traversal

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/buildTree.py
