### ISSUE TITLE
22. Generate Parentheses

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#14]
Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

For example, given n = 3, a solution set is:

[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
]

- [x] code submit by yuyang

- [x] code submit by jinglonz

- [ ] discuss

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/generateParenthesis.py

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/LeeMax/22_Generate_Parentheses.py
