### ISSUE TITLE
46. Permutations

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#15]
Given a collection of distinct integers, return all possible permutations.

Example:

Input: [1,2,3]
Output:
[
  [1,2,3],
  [1,3,2],
  [2,1,3],
  [2,3,1],
  [3,1,2],
  [3,2,1]
]

- [x] code submit by yuyang

- [x] code submit by jinglonz

- [ ] discuss

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/Permutations.py

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/LeeMax/46_Permutations.py
