### ISSUE TITLE
1023: camelMatch

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#3]
如果我们可以将小写字母插入模式串 pattern 得到待查询项 query，那么待查询项与给定模式串匹配。（我们可以在任何位置插入每个字符，也可以插入 0 个字符。）

给定待查询列表 queries，和模式串 pattern，返回由布尔值组成的答案列表 answer。只有在待查项 queries[i] 与模式串 pattern 匹配时， answer[i] 才为 true，否则为 false。

 

示例 1：

输入：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FB"
输出：[true,false,true,true,false]
示例：
"FooBar" 可以这样生成："F" + "oo" + "B" + "ar"。
"FootBall" 可以这样生成："F" + "oot" + "B" + "all".
"FrameBuffer" 可以这样生成："F" + "rame" + "B" + "uffer".
示例 2：

输入：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FoBa"
输出：[true,false,true,false,false]
解释：
"FooBar" 可以这样生成："Fo" + "o" + "Ba" + "r".
"FootBall" 可以这样生成："Fo" + "ot" + "Ba" + "ll".
示例 3：

输出：queries = ["FooBar","FooBarTest","FootBall","FrameBuffer","ForceFeedBack"], pattern = "FoBaT"
输入：[false,true,false,false,false]
解释： 
"FooBarTest" 可以这样生成："Fo" + "o" + "Ba" + "r" + "T" + "est".

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/LeeMax/1023_Camelcase%20Matching.py

**Comment by nijilong1224** [comment]
class Solution:
    def camelMatch(self, queries: List[str], pattern: str) -> List[bool]:
        out_list = []
        l2 = len(pattern)
        for query in queries:
            l1 = len(query)
            cnt = 0
            flag = True
            for i in range(l1):
                if cnt < l2:
                    if query[i] > 'Z' and query[i] != pattern[cnt]:
                        continue
                    elif query[i] < 'a' and query[i] != pattern[cnt]:
                        flag = False
                        break
                    cnt = cnt + 1
                else:
                    if query[i] < 'a':
                        flag = False
                        break
            out_list.append(cnt == l2 and flag)
        return out_list

**Comment by nijilong1224** [comment]
`class Solution:
    def camelMatch(self, queries: List[str], pattern: str) -> List[bool]:
        out_list = []
        l2 = len(pattern)
        for query in queries:
            # out_list.append(self.queryMatch(query, pattern))
            l1 = len(query)
            cnt = 0
            flag = True
            for i in range(l1):
                if cnt < l2:
                    if query[i] > 'Z' and query[i] != pattern[cnt]:
                        continue
                    elif query[i] < 'a' and query[i] != pattern[cnt]:
                        flag = False
                        break
                    cnt = cnt + 1
                else:
                    if query[i] < 'a':
                        flag = False
                        break
            out_list.append(cnt == l2 and flag)
        return out_list`

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/camelMatch.py
