### ISSUE TITLE
395. Longest Substring with At Least K Repeating Characters

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#5]
**Description:**
Find the length of the longest substring T of a given string (consists of lowercase letters only) such that every character in T appears no less than k times.

Example 1:

Input:
s = "aaabb", k = 3

Output:
3

The longest substring is "aaa", as 'a' is repeated 3 times.
Example 2:

Input:
s = "ababbc", k = 2

Output:
5

The longest substring is "ababb", as 'a' is repeated 2 times and 'b' is repeated 3 times.

**Process:**
- [x] Jionglong's Code
- [x] LeeMax's code
- [x] Discuss & Improve

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/longestSubstring.py

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/tree/master/LeeMax/395_longestSubstring
