### ISSUE TITLE
31. Next permutation

### ISSUE THREAD

**Issue by nijilong1224** [LeeMax117/LeetCode_practise#8]
Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.

If such arrangement is not possible, it must rearrange it as the lowest possible order (ie, sorted in ascending order).

The replacement must be in-place and use only constant extra memory.

Here are some examples. Inputs are in the left-hand column and its corresponding outputs are in the right-hand column.

1,2,3 → 1,3,2
3,2,1 → 1,2,3
1,1,5 → 1,5,1
- [x] submit code by jinglong
- [x] submit  code by yuyang
- [x] discuss

**Comment by LeeMax117** [comment]
https://github.com/LeeMax117/LeetCode_practise/tree/master/LeeMax/31_next_permutation

**Comment by nijilong1224** [comment]
https://github.com/LeeMax117/LeetCode_practise/blob/master/Jinglong/nextPermutation.py
